name: "Setup project"
runs:
  using: "composite"
  steps:
  - if: runner.os == 'macOS'
    run: brew install age swift-format
    shell: bash

  - if: runner.os == 'Linux'
    run: |
      # Age on current Ubuntu doesn't support plugins
      # sudo apt-get update
      # sudo apt-get install age
      curl -L -s https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz  | tar xvz
      echo "$GITHUB_WORKSPACE/age" >> $GITHUB_PATH
    shell: bash

  # Using a downloaded version of Swift for now, because the system version 
  # suddenly broke. Using 5.7, because 5.8 breaks the coverage option. Fixed in 5.9.
  - if: runner.os == 'macOS'
    run: |
      curl -L -s -o swift.pkg https://download.swift.org/swift-5.7.3-release/xcode/swift-5.7.3-RELEASE/swift-5.7.3-RELEASE-osx.pkg
      # Can't find where it installed swift.
      # sudo installer -pkg swift.pkg -verbose -dumplog -target /
      tar xvf swift.pkg 
      tar xvf swift-5.7.3-RELEASE-osx-package.pkg/Payload
      echo "$GITHUB_WORKSPACE/usr/bin" >> $GITHUB_PATH
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      curl -L -s https://download.swift.org/swift-5.7.3-release/ubuntu2204/swift-5.7.3-RELEASE/swift-5.7.3-RELEASE-ubuntu22.04.tar.gz | tar xvz 
      echo "$GITHUB_WORKSPACE/swift-5.7.3-RELEASE-ubuntu22.04/usr/bin" >> $GITHUB_PATH
    shell: bash


  - if: runner.os == 'Windows'
    run: choco install age.portable
    shell: pwsh
  - if: runner.os == 'Windows'
    uses: compnerd/gha-setup-swift@main
    with:
      branch: swift-5.8-release
      tag: 5.8-RELEASE
