name: "Setup project"
runs:
  using: "composite"
  steps:
  - if: runner.os == 'macOS'
    run: brew install age swift-format
    shell: bash
  - if: runner.os == 'Linux'
    run: |
      # Age on current Ubuntu doesn't support plugins
      # sudo apt-get update
      # sudo apt-get install age
      curl -L -s https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz  | tar xvz
      echo "$GITHUB_WORKSPACE/age" >> $GITHUB_PATH
    shell: bash
  - if: runner.os == 'Windows'
    run: choco install age.portable
    shell: pwsh
  - if: runner.os == 'Windows'
    uses: compnerd/gha-setup-swift@main
    with:
      branch: swift-5.8-release
      tag: 5.8-RELEASE
