name: Build

on:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        # FIXME: Doesn't work on macOS yet, since we use macOS 13 APIs
        # https://github.com/actions/runner-images/issues/6426
        # https://github.com/github/roadmap/issues/620
        os: [ubuntu-22.04] # macos-13,
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: make
      - run: make test COVERAGE=1
      - run: make smoke-test-encrypt
      - run: make lint
        # We don't have swift-format on Linux yet
        if: runner.os == 'macOS'

      # Our own simplified version of github pages upload
      - run: |
          tar -C .build -czf github-pages.tar.gz coverage.svg
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: github-pages.tar.gz
        if: runner.os == 'Linux'

  # Running swift from the Makefile doesn't work (yet), so we have a separate
  # build procedure for windows.
  # FIXME: Fix the build again
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/setup
  #     - run: swift build
  #     # Unit tests don't seem to work yet
  #     # - run: swift test
  #     - name: Run smoke test
  #       run: |
  #         $Env:Path += ";" + (swift build --show-bin-path)
  #         echo "test" | age --encrypt --recipient age1se1qgg72x2qfk9wg3wh0qg9u0v7l5dkq4jx69fv80p6wdus3ftg6flwg5dz2dp -o secret.txt.age
